# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: daa12aa104c6249928f37ca6bbd1e83af58c19f8adf4569f3793125158a10953a0eece3d4914c86d3f0dd242b7e2afca867259acfc8873dca15c34cc8e889476

test:
  secret_key_base: 66bf5148fc940c1c9f658a21004e490104aeac2c087d6bf4c2168838fedf41acfabd44872d205ce9ada5778e1e57a972b43666c5a664be2596385da243a09821

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
